packages:
  - apache2
  - libapache2-mod-php7.1
  - php7.1 
  - php7.1-common 
  - php7.1-mbstring 
  - php7.1-xmlrpc 
  - php7.1-soap 
  - php7.1-gd 
  - php7.1-xml 
  - php7.1-intl 
  - php7.1-mysql 
  - php7.1-cli 
  - php7.1-mcrypt 
  - php7.1-zip 
  - php7.1-curl
  - percona-server-server-5.7
  - percona-server-common-5.7
  - percona-server-client-5.7


paths:
  old:
    - "/etc/httpd"
    - "/etc/nginx"
    - "/home/bitrix/ext_www"
  new: 
    - "/etc/apache2"
    - "/etc/nginx"
    - "/home/bitrix/ext_www"