packages:
  - nginx-extras
  - libmysqlclient-dev
  - apache2
  - libapache2-mod-php7.1
  - php7.1 
  - php7.1-common 
  - php7.1-mbstring 
  - php7.1-xmlrpc 
  - php7.1-soap 
  - php7.1-gd 
  - php7.1-xml 
  - php7.1-intl 
  - php7.1-mysql 
  - php7.1-cli 
  - php7.1-mcrypt 
  - php7.1-zip 
  - php7.1-curl
  - percona-server-server-5.7
  - percona-server-common-5.7
  - percona-server-client-5.7

users: 
  - { name: "bitrix", groups: "", append: "no"}

permissions:
  - { path: "/etc/apache2/bx/", perm: "0644", user: "bitrix", group: "bitrix" }
  - { path: "/etc/apache2/apache2.conf", perm: "0644", user: "bitrix", group: "bitrix" }
  - { path: "/etc/nginx/nginx.conf", perm: "0644", user: "bitrix", group: "bitrix" }
  - { path: "/etc/nginx/bx/site_avaliable", perm: "0644", user: "bitrix", group: "bitrix" }
  - { path: "/etc/nginx/bx/conf", perm: "0644", user: "bitrix", group: "bitrix" }
  - { path: "/etc/nginx/bx/maps", perm: "0644", user: "bitrix", group: "bitrix" }
  - { path: "/etc/nginx/openssl.cnf", perm: "0644", user: "bitrix", group: "bitrix" }


